version: '1'
services:
  dionaea:
    image: isif/dionaea0.8:version1
    volumes:
      - ./dionaea.sysconfig:/etc/default/dionaea
      - ./dionaea/dionaea:/etc/dionaea/
    ports:
      - "21:21"
      - "23:23"
      - "69:69"
      - "80:80"
      - "123:123"
      - "135:135"
      - "443:443"
      - "445:445"
      - "1433:1433"
      - "1723:1723"
      - "1883:1883"
      - "1900:1900"
      - "3306:3306"
      - "5000:5000"
      - "5060:5060"
      - "5061:5061"
      - "11211:11211"
      - "27017:27017"
    cap_add:
      - NET_ADMIN
